server:
  port: 9999
spring:
  application:
    name: es-article

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/leadnews_article?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: dez10160830

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.heima.model.user.pojos

elasticsearch:
  host: 127.0.0.1
  port: 9200